version: '3.8'

services:
  jekyll:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jekyll-${STAGE:-staging}.rule=Host(`${APP_FQDN:-localhost}`)'
      - 'traefik.http.routers.jekyll-${STAGE:-staging}.entrypoints=web'
      - 'traefik.http.routers.jekyll-${STAGE:-staging}.middlewares=redirect-to-https'
      - 'traefik.http.routers.jekyll-${STAGE:-staging}-tls.rule=Host(`${APP_FQDN:-localhost}`)'
      - 'traefik.http.routers.jekyll-${STAGE:-staging}-tls.entrypoints=websecure'
      - 'traefik.http.routers.jekyll-${STAGE:-staging}-tls.tls.certresolver=default-tls'
      - 'traefik.http.services.jekyll-${STAGE:-staging}.loadbalancer.server.port=8080'
    networks:
      - traefik_default
      - default

networks:
  traefik_default:
    external: true
